### ISSUE TITLE
Crash when deleting last follower

### ISSUE THREAD

**Issue by brockenbrough** [brockenbrough/ssu-social-frontend#38]
Go to profile.
Click on following.
Delete all your followers.
You get this error:
![image](https://github.com/user-attachments/assets/d59f4aae-ef4e-4c98-be04-f983ea0f9d52)

**Comment by karanssu** [comment]
The issue has been resolved. The problem was that the Follow button was expecting an onUpdateFollowerCount function in the props, but it wasn't provided consistently throughout the system where it was used.

You can see the fix in this commit: https://github.com/brockenbrough/ssu-social-frontend/commit/06ad9fcf44910abee963a5013e721c11291e5936
