### ISSUE TITLE
Access token is not secure - can be decrypt and reused as someone else.

### ISSUE THREAD

**Issue by brockenbrough** [brockenbrough/ssu-social-frontend#72]
The access token can be decoded (that's not a problem), but the decoded content is in plain text.  The text can then be changed (you could alter the username), and then you could re-use the token to masquerade as someone else.  

Notes: For more information, talk to theProfessor or Yogesh.

**Comment by Grummps** [comment]
Fixed by creating and using a refreshToken that'll confirm if the accessToken can be refreshed.
Commits:
https://github.com/brockenbrough/ssu-social-frontend/commit/c5680fb30496b379cbf9e2c628afec8dfa711f78
https://github.com/brockenbrough/ssu-social-backend/commit/5f753f3308146aeae44fc01ec42a48b503fabc67
